import React from "react";
import DataSelect from "./Select/DataSelect";
import Header from "@bit/viz.spectrum.header";

import {withRouter} from "react-router";
import ReDim from "./ReDim/ReDim";
const title = "scRNA Dashboard";
const description =
  "An interactive visualization for single cell RNA (scRNA) QC data, as generated by the scRNA-seq pipeline (https://github.com/shahcompbio/SCRNApipeline)";
const App = ({location}) => {
  const [patientID, sampleID] = location.pathname.substr(1).split("/");

  return (
    <div style={{width: "100%"}}>
      <Header name={title} description={description} />
      <div className="App" style={AppStyles}>
        <DataSelect patientID={patientID} sampleID={sampleID} />
        <ReDim patientID={patientID} sampleID={sampleID} />
      </div>
    </div>
  );
};

const AppStyles = {
  width: "100vw",
  height: "100%",
  display: "flex",
  padding: "25px",
  justifyContent: "space-between",
  alignItems: "flex-start",
  flexDirection: "column"
};

export default withRouter(App);
